CREATE TABLE `DOC_PROCESSING_REQUEST` (
  `ID` varchar(36) NOT NULL,
  `OBJ_VERSION` int(11) NOT NULL,
  `ACCOUNT_NUMBER` varchar(12) NOT NULL,
  `ACCOUNT_VERIFIED` BOOLEAN NOT NULL,
  `ID_DOC_TYPE` varchar(255) NOT NULL,
  `FRONT_SIDE_ID_DOC` blob NOT NULL,
  `BACK_SIDE_ID_DOC` blob,
  `SELFIE` blob NOT NULL,
  `ID_DOC_EXPIRATION` date,
  `STATUS` varchar(255) NOT NULL,
  `DENIED_REASON` varchar(255),
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX IDX_DOC_PROCESSING_REQUEST_ACCOUNT_NUMBER ON DOC_PROCESSING_REQUEST (ACCOUNT_NUMBER);

